services:
  - type: web
    name: indio-bot-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POOLSIDE_API_KEY
        sync: false
      - key: RESERVAS_ACTIVAS
        value: "False"
      - key: GOOGLE_CLIENT_ID
        sync: false
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        sync: false
        value: ""
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
        value: ""